name: vamba
channels:
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pytorch=2.2.2
  - torchvision=0.17.2
  - pytorch-cuda=11.8
  - numpy=1.26.4
  - pip
  - pip:
    - av==11.0.0
    - decord==0.6.0
    - deepspeed==0.14.2
    - einops==0.7.0
    - ftfy==6.1.3
    - fvcore==0.1.5.post20221221
    - imageio==2.33.1
    - lm_eval==0.4.1
    - omegaconf==2.3.0
    - opencv_python==4.8.1.78
    - packaging==24.0
    - pandas==2.2.1
    - Pillow==10.1.0
    - pytest==8.1.1
    - PyYAML==6.0.1
    - regex==2023.10.3
    - Requests==2.31.0
    - scipy==1.12.0
    - setuptools==68.2.2
    - scikit-image
    - submitit==1.5.1
    - tensorboardX==2.6.2.2
    - termcolor==2.4.0
    - timm==0.4.12
    - tqdm==4.66.1
    - transformers==4.44.0
    - wandb==0.16.2
    - wheel==0.42.0
    - sentencepiece==0.2.0
    - bitsandbytes==0.43.1
    - easydict==1.13
    - pysubs2==1.7.3
    - fire==0.6.0
    - mambapy==1.2.0
    - causal-conv1d==1.4.0
    - qwen_vl_utils==0.0.10
    - calflops==0.3.2