captioning_templates = {
    "user": [
        "Describe what is happening in this {}.",
        "What is shown in the {}?",
        "Explain the content of this {}.",
        "What can be seen in the {}?",
        "Summarize what is depicted in the {}.",
        "What does the {} illustrate?",
        "Provide a description of the {}.",
        "What is the scene in the {} about?",
        "Detail what occurs in the {}.",
        "What story does the {} tell?",
        "Describe the events in the {}.",
        "What can you observe in the {}?",
        "Explain the scenario in the {}.",
        "What is the main focus of the {}?",
        "Outline what happens in the {}.",
        "What is the highlight of the {}?",
        "Describe the activity in the {}.",
        "What is the {} showing?",
        "Give an overview of the {} content.",
        "What is captured in the {}?",
    ],
    "assistant": [
        "The {} shows {}.",
        "In the {}, {}.",
        "The content of the {} is {}.",
        "The {} illustrates {}.",
        "The scene in the {} describes {}.",
        "The {} depicts {}.",
        "According to the {}, {}.",
        "The {} portrays {}.",
        "The {} demonstrates {}.",
        "The {} reveals {}.",
        "The {} conveys {}.",
        "The {} captures {}.",
        "The {} narrates {}.",
        "As shown in the {}, {}.",
        "The {} tells the story of {}.",
        "The {} represents {}.",
        "From the {}, we see {}.",
        "The {} describes {}.",
        "The {} presents {}.",
        "The {} features {}.",
    ]
}